In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print (x)

[['Kursi' 2 72000]
 ['Meja' 3 150000]
 ['Lemari' 1 500000]
 ['Kursi' 2 72000]
 ['Meja' 3 150000]
 ['Lemari' 1 500000]
 ['Kursi' 2 72000]
 ['Meja' 3 150000]
 ['Lemari' 1 500000]
 ['Kursi' 2 72000]]


In [ ]:
print (y)

['No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print (x)

[['Kursi' 2.0 72000.0]
 ['Meja' 3.0 150000.0]
 ['Lemari' 1.0 500000.0]
 ['Kursi' 2.0 72000.0]
 ['Meja' 3.0 150000.0]
 ['Lemari' 1.0 500000.0]
 ['Kursi' 2.0 72000.0]
 ['Meja' 3.0 150000.0]
 ['Lemari' 1.0 500000.0]
 ['Kursi' 2.0 72000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print (x)

[[1.0 0.0 0.0 2.0 72000.0]
 [0.0 0.0 1.0 3.0 150000.0]
 [0.0 1.0 0.0 1.0 500000.0]
 [1.0 0.0 0.0 2.0 72000.0]
 [0.0 0.0 1.0 3.0 150000.0]
 [0.0 1.0 0.0 1.0 500000.0]
 [1.0 0.0 0.0 2.0 72000.0]
 [0.0 0.0 1.0 3.0 150000.0]
 [0.0 1.0 0.0 1.0 500000.0]
 [1.0 0.0 0.0 2.0 72000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print (y)

[0 1 1 0 0 1 1 0 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print (x_train)

[[1.0 0.0 0.0 2.0 72000.0]
 [0.0 0.0 1.0 3.0 150000.0]
 [1.0 0.0 0.0 2.0 72000.0]
 [1.0 0.0 0.0 2.0 72000.0]
 [0.0 0.0 1.0 3.0 150000.0]
 [0.0 0.0 1.0 3.0 150000.0]
 [0.0 1.0 0.0 1.0 500000.0]
 [0.0 1.0 0.0 1.0 500000.0]]


In [ ]:
print (x_test)

[[0.0 1.0 0.0 1.0 500000.0]
 [1.0 0.0 0.0 2.0 72000.0]]


In [ ]:
print (y_train)

[1 0 0 0 1 0 0 1]


In [ ]:
print (y_test)

[1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print (x_train)

[[1.0 0.0 0.0 -0.16012815380508713 -0.7930975587556829]
 [0.0 0.0 1.0 1.12089707663561 -0.33906739667903507]
 [1.0 0.0 0.0 -0.16012815380508713 -0.7930975587556829]
 [1.0 0.0 0.0 -0.16012815380508713 -0.7930975587556829]
 [0.0 0.0 1.0 1.12089707663561 -0.33906739667903507]
 [0.0 0.0 1.0 1.12089707663561 -0.33906739667903507]
 [0.0 1.0 0.0 -1.4411533842457842 1.698247433152077]
 [0.0 1.0 0.0 -1.4411533842457842 1.698247433152077]]


In [ ]:
print (x_test)

[[0.0 1.0 0.0 -1.4411533842457842 1.698247433152077]
 [1.0 0.0 0.0 -0.16012815380508713 -0.7930975587556829]]
